### PR TITLE
1.11

### PR DESCRIPTION
**Pull request by methnen**
* Added a Chart Block for the WordPress Block Editor
	* Send your thanks to [webconstructor](https://github.com/webconstructor) for lion's share of the work on this
* Added a [CSV Delimiter](https://github.com/methnen/m-chart/wiki/csv-importing-exporting) contro and setting to allow for differences in CSV files from different regions
* Fixed an issue where data points weren't being cleaned well enough and it could confuse Chart.js
* Fixed an issue where Chart.js tooltips sometimes duplicated a label
* Fixed an issue with entities inside of labels

https://github.com/methnen/m-chart/issues/184
https://github.com/methnen/m-chart/issues/134

### CODE REVIEW

**Comment by webconstructor** [comment]
Nice, 2 things only
* I would like a little margin bottom in the backend on the block: wp-block m-chart-selector so the borders have some breathing space
* I am very happy with the import seperator option yet I would more expect it on the import / create graph page instead of as a general setting.
That way it is easier to have a different seperator for each graph. I tested switching after uploading and all already downloaded graphs still worked so there is a way to do so now but still...

The code is nicely organised. Perhaps remove the commented boxshadow.

**Comment by methnen** [comment]
Thanks @webconstructor, I'll get that margin added in. 

And that's a greatidea on the CSV handling. I'll make it work that way instead.

**Comment by methnen** [comment]
@webconstructor can you clarify on the margins a bit? I'm not quite sure where you're referring to.

**Comment by methnen** [comment]
@webconstructor This has been updated to include the CSV import changes and a fix for the doubled labels on the tooltips. Let me know if that seems good on your end?

Also still looking for some clarification on the additional margin you wanted.

**Comment by webconstructor** [comment]
Wow Methen, great stuff. 

- Label issue fixed
- A separator default and an option to change it per graph

Very very nice.

Considering the margin
This is in the backend mainly (although the frontend may need it as well). 
Blocks are stacked vertically so the borders of the chart-selector when using multiple charts without text in between hit each other.
`.m-chart-selector: 1.5rem; `
would fix that

**Comment by methnen** [comment]
When I'm in the block view I see something that looks like this:

image

There's already some reasonable padding between block elements. I think this might be a theme related issue.

**Comment by methnen** [comment]
@webconstructor Just a heads up I think this is ready to go out. Unless you see any last minute issues my plan is to merge this tonight and then push submit it to wordpress.org.  Probably around 10PM Pacific.

**Comment by webconstructor** [comment]
No, no issues here
You're right about the margin in your screenshot
Can't wait for the release
A small step for man...

**Comment by methnen** [comment]
I mean to get this out on the weekend but life intervened. I'll be shooting to launch it sometime this evening now instead.

**Pull request merged**
