### PR TITLE
fix-php-deprecated-messages-in-debug-log

### PR DESCRIPTION
**Pull request by webconstructor**
https://wordpress.org/support/topic/simple-to-fix-php-notice/

### CODE REVIEW

**Comment by methnen** [comment]
@webconstructor thanks for the pull request. I've repointed it at 1.10.1 branch which I'll throw a few other smaller fixes into and will push it out in the next version.

**Comment by methnen** [comment]
@webconstructor You don't happen be related to the belastingdienst.nl folks who messaged me a couple of days ago? I'd be happy to jump on a quick Zoom call or something along those lines if you wanted to communicate a bit on what kinds of plans you guys had.

I'll warn you though my dutch is non existent. :)

**Comment by webconstructor** [comment]
> @webconstructor You don't happen be related to the belastingdienst.nl folks who messaged me a couple of days ago? I'd be happy to jump on a quick Zoom call or something along those lines if you wanted to communicate a bit on what kinds of plans you guys had.
> 
> I'll warn you though my dutch is non existent. :)

Hi Jamie
Well sensed. I am a member of that theme: one of the 4 webdevs. 
I found your plugin, found it very usefull & introduced it in the team. 
The debug notices is really a showstopper for us so I thought I'd make the solution of it one click away for you...

Ben contacted you for he is the one who will use the plugin.

We are still formulating our plans and love to have an online meeting with you once we have our ideas and wishes clear.
We 'll contact you than.

Regards Inigo

P.s. English will not be a problem ;-)

**Comment by methnen** [comment]
Sounds like a plan.

**Comment by webconstructor** [comment]
How about wednesday 14-6 at 11:00?

**Comment by methnen** [comment]
That should work for me.

**Comment by webconstructor** [comment]
Hmmm, Ben made a mistake in his calander.
Could we meet at 18:30 / 9:30?
I send you an email with a url of our meeting channel.

Hope to see you today

**Comment by methnen** [comment]
Was just wondering if you guys were gonna send something :)

9:30AM Pacific should work.

> On Jun 20, 2023, at 3:48 AM, Inigo ***@***.***> wrote:
> 
> 
> Hmmm, Ben made a mistake in his calander.
> Could we meet at 18:30 / 9:30?
> I send you an email with a url of our meeting channel.
> Hope to see you today
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

Jamie

"And we are drowned."
-Annie Dillard (Tickets For a Prayer Wheel)

**Pull request merged**
