### PR TITLE
Fixed stretched out images, to generate better looking images

### PR DESCRIPTION
**Pull request by jidefela**

### CODE REVIEW

**Comment by jidefela** [comment]
Fixed stretched images

**Comment by jidefela** [comment]
@methnen Thank you for your response. Also, my apologies for the delayed response. This is my very first public PR :) 

To provide some context, while developing this plugin at my company [Print PDF Generator and Publisher](https://wordpress.org/plugins/nopeamedia/),  we needed a way for the users to add charts to pdf content, and this plugin seem like a good solution, thanks to you !. 
We added a parser to interchange the chart shortcodes for the generated png images while generating the pdf. But the image didn't look so good, hence the fix. 
Pls see below, before and after images for comparism.
**Before** before
**After** after

**Comment by methnen** [comment]
@jidefela I realize it's taken me FOREVER to get around to getting this out but I'm very close to finishing up a fairly major update to the plugin.

As part of that I integrated a fix for this stretching issue but I want to confirm that it works for you in your situation because I ended up going about it in a different manner.

Could you take a look and try out the 1.8 branch and tell me if it seems to handle the image stuff correctly for you?

https://github.com/methnen/m-chart/tree/1.8

Feel free to note any other issues you notice as well. :)

**Comment by jidefela** [comment]
Hi @methnen, thanks for the update. 

I ran some test with the new version 1.8. It seems to works fine. 

Is it possible to increase the resolution so that the labels have clearer text ?

**Comment by methnen** [comment]
I've been contemplating a 1x 2x 3x selector for the image size.

Basically it's 2x as currently done. But with screen sizes and pixel density what it is these days a 3x does make sense.

so it would 600 width 1200 width and 1800 width with the height value at the 1, 2, or 3 x multiplier.

I can probably get that in for this next release. I'm hoping to get it out sometime this week.

**Comment by methnen** [comment]
@jidefela can you take a look at most recent version of the 1.8 brand and let me know if it works for you?

I've pretty significantly reworked how the image generation stuff works for Chart.js as well as added a Image Multiplier option (in the plugin settings) that allows you to control the multiplier at which the images are resized.

The first bit should solve any blurry image issues you were having and the multiplier option should  let you get a very high res image to work with if you want it.

**Comment by methnen** [comment]
Closing since this has been subsumed by the 1.8 pull request.

https://github.com/methnen/m-chart/pull/141

**Pull request closed without merging**
